# Enhanced YouTube Configuration for Bot Detection Bypass
# Replace the ytdl_format_options in your bot.py with this configuration

ytdl_format_options = {
    'format': 'bestaudio/best',
    'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
    'restrictfilenames': True,
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': True,
    'logtostderr': False,
    'quiet': True,
    'no_warnings': True,
    'default_search': 'auto',
    'source_address': '0.0.0.0',
    'force_ssl': False,
    'prefer_insecure': True,
    'socket_timeout': 30,
    'retries': 5,
    'fragment_retries': 5,
    'skip_unavailable_fragments': True,
    'keep_fragments': False,
    'buffersize': 16384,
    'noresizebuffer': True,
    'http_chunk_size': 10485760,
    'playlist_items': '1',
    'extract_flat': False,
    'mark_watched': False,
    'merge_output_format': 'mp4',
    'writeinfojson': False,
    'writesubtitles': False,
    'writeautomaticsub': False,
    'allsubtitles': False,
    'listsubtitles': False,
    'subtitlesformat': 'best',
    'subtitleslangs': ['en'],
    'matchtitle': None,
    'rejecttitle': None,
    'max_downloads': 1,
    'prefer_free_formats': True,
    'verbose': False,
    'dump_intermediate_pages': False,
    'write_pages': False,
    'load_pages': False,
    'youtube_include_dash_manifest': False,
    'extractor_args': {
        'youtube': {
            'skip': ['dash', 'hls'],
            'player_client': ['android', 'android_music', 'android_creator', 'androidtv'],
            'player_skip': ['configs', 'webpage'],
            'comment_sort': ['top'],
            'max_comments': [0],
            'innertube_host': ['youtubei.googleapis.com'],
            'innertube_key': ['AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8'],
        }
    },
    'http_headers': {
        'User-Agent': 'Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-us,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate',
        'DNT': '1',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Cache-Control': 'max-age=0',
    }
}
